version: 2
jobs:
  build:
    docker:
        - image: circleci/python:3.7
        - image: circleci/postgres:9.6-alpine-ram
          environment:
            POSTGRES_PASSWORD: verde3

    steps:
      - checkout
      - run:
          name: Run Tests
          command: make test
