version: "3.5"
services:

  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - unigator
    environment:
      POSTGRES_PASSWORD: verde3
    ports:
      - "5432:5432"

volumes:
  db-data:

networks:
  unigator:
    name: unigator
